In [12]:
class construction:
    
    def __init__(self, str1='con', str2='con2'):
        self.str1 = str1
        self.str2 = str2

In [13]:
contents = construction()
print(contents.str1)

con


In [16]:
import numpy as np
d = np.array([1,2,3,4,4,3,5,3,6])
haa = np.flatnonzero(d == 3)
print(haa)

[2 5 7]


In [15]:
import numpy as np
x = np.ones([4, 4]) * 1
y = np.ones([4, 4]) * 2
z = np.ones([4, 4]) * 3

def add_forward():
    cache = (x, y, z)
    out = np.ones(4, 4) * 4
    return out, cache
def check(af, xx, yy):
    ans = af
    return ans

test = check(lambda x: add_forward(x, y, z)[0], x, y)
print(test)

<function <lambda> at 0x000001AA1053C510>


In [6]:
import numpy as np
import random
x = np.linspace(1, 20, num=20).reshape(4,5)
x = x[[1, 1], :]
print(x)

[[ 6.  7.  8.  9. 10.]
 [ 6.  7.  8.  9. 10.]]


In [40]:
import numpy as np
x = np.array([[0, 1, 2], [2, 3 ,4]])
print(x[0:1,0:3])

[[0 1 2]]
